config/routes.rb
Rails.application.routes.draw do

  root 'songs#index'

    resources :songs

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :genre
  has_many :album_songs
  has_many :songs, through: :album_songs
end

app/models/album_song.rb
class AlbumSong < ActiveRecord::Base
  belongs_to :album
  belongs_to :song
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :songs
  has_many :albums
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :genre
  has_many :albums, through: :album_songs
  has_many :album_songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    binding.pry
    @song = Song.find(params[:id])
  end

  def new
    #instantiate an empty footballer object
    @song = Song.new
  end

  def create
    Song.create(song_params)
    redirect_to(songs_path)
  end

  def edit
  @song = Song.find(params[:id])
  end

  def update
  #   #binding.pry
  #   #look up the planet in the planets database
    @song = Song.find(params[:id])
    #update the attributes
    @song.update(song_params)
    redirect_to(songs_path)
  end

  def destroy
    #binding.pry
    #Look up the planet in the database using the id from params
    song = Song.find(params[:id]).destroy
    song.destroy
    #Delete planet from the database
    redirect_to(songs_path)
  end

   private
  #this is a security method that allows you to update the following columns in the database
  def song_params
    params.require(:song).permit(:name, :artist)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TunrApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:action]%>">
<li><%= link_to('NEW SONG', new_song_path)%></li>


<h1>HELLO</h1>
<%= yield %>

</body>
</html>

app/views/songs/index.html.erb
<div class="song-list">
<% @songs.each do |song| %>
 <div class="list-group-item">
 <%= link_to song_path(song.id) do %>
 <%end%>
<ul class="song">

    <li><%=link_to(song.name,song_path(song.id))%>
    <% song.albums.each do |album| %>
      <%= album.name %>
    <%end%>
    </li>
    <li><%= link_to('NEW SONG', new_song_path)%></li>
    <li><%=link_to('EDIT', edit_song_path(song.id))%></li>
    <li><%=link_to('DELETE',song_path(song.id), method: :delete) %></li>


      </ul>
    </div>
  <%end%>
</div>

app/views/songs/new.html.erb
<%= form_for @song do |f| %>

<%=f.label :name %>
<%=f.text_field :name %>

<%=f.label :artist %>
<%=f.text_field :artist %>

<%=f.label :price %>
<%= f.text_field :price %>

<%= f.submit 'CREATE SONG'%>

<%end%>